# Generated by Django 4.0 on 2021-12-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
